package fr.rca.mapmaker.io.playdate;

import fr.rca.mapmaker.io.DataHandler;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

/**
 *
 * @author Raphaël Calabro (raphael.calabro.external2@banque-france.fr)
 */
public class AnimationNameAsHeaderHandler implements DataHandler<List<String>> {

	@Override
	public void write(List<String> t, OutputStream outputStream) throws IOException {
		final SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
		outputStream.write(("//\n"
				+ "// animationnames.h\n"
				+ "//\n"
				+ "// Generated by MapMaker on " + dateFormat.format(new Date()) + ".\n"
				+ "//\n"
				+ "\n"
				+ "#ifndef animationnames_h\n"
				+ "#define animationnames_h\n"
				+ "\n"
				+ "#include <stdio.h>\n"
				+ "\n"
				+ "#include \"../lib/melice.h\"\n"
				+ "\n"
				+ "#define kAnimationNameCount " + t.size() + "\n"
				+ "\n"
				+ "typedef enum {\n").getBytes(StandardCharsets.UTF_8));

		for (String animationName : t) {
			outputStream.write(("    AnimationName" + Names.toPascalCase(animationName) + ",\n").getBytes(StandardCharsets.UTF_8));
		}

		outputStream.write(("} AnimationName;\n"
				+ "\n"
				+ "#endif /* animationnames_h */\n").getBytes(StandardCharsets.UTF_8));
	}

	@Override
	public List<String> read(InputStream inputStream) throws IOException {
		throw new UnsupportedOperationException("Not supported.");
	}

	@Override
	public String fileNameFor(List<String> t) {
		return "animationnames.h";
	}

}
