package fr.rca.mapmaker.io.playdate;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Raphaël Calabro (raphael.calabro.external2@banque-france.fr)
 */
public class Headers {
	public static String getGeneratedDate(File file) {
		try (BufferedReader reader = new BufferedReader(
				new InputStreamReader(new FileInputStream(file), StandardCharsets.UTF_8))) {
			final Pattern pattern = Pattern.compile("Generated by MapMaker on ([0-9]{2}\\/[0-9]{2}\\/[0-9]{4}).");
			String line = reader.readLine();
			while (line != null) {
				final Matcher matcher = pattern.matcher(line);
				if (matcher.find()) {
					return matcher.group(1);
				}
				line = reader.readLine();
			}
		} catch (IOException e) {
			// Ignoré
		}
		return getGeneratedDate();
	}

	public static String getGeneratedDate() {
		return new SimpleDateFormat("dd/MM/yyyy").format(new Date());
	}
}
