package fr.rca.mapmaker.editor;

import fr.rca.mapmaker.model.map.PaletteMap;

/**
 *
 * @author Raphaël Calabro (rcalabro@ideia.fr)
 */
public class TileMapEditor extends javax.swing.JDialog {
	
	private static final int PALETTE_WIDTH = 8;

	/**
	 * Creates new form TileMapEditor
	 */
	public TileMapEditor(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        toolButtonGroup = new javax.swing.ButtonGroup();
        drawMap = new fr.rca.mapmaker.model.map.TileMap();
        colorPalette = new fr.rca.mapmaker.model.palette.ColorPalette();
        gridScrollPane = new javax.swing.JScrollPane();
        centerPanel = new javax.swing.JPanel();
        grid = new fr.rca.mapmaker.ui.Grid();
        paletteGrid = new fr.rca.mapmaker.ui.Grid();
        selectionToggleButton = new javax.swing.JToggleButton();
        magicWandToggleButton = new javax.swing.JToggleButton();
        penToggleButton = new javax.swing.JToggleButton();
        bucketFillToggleButton = new javax.swing.JToggleButton();
        lineToggleButton = new javax.swing.JToggleButton();
        circleToggleButton = new javax.swing.JToggleButton();
        rectangleToggleButton = new javax.swing.JToggleButton();
        rectangleFillToggleButton = new javax.swing.JToggleButton();
        ellipseToggleButton = new javax.swing.JToggleButton();
        ellipseFillToggleButton = new javax.swing.JToggleButton();
        colorPickerToggleButton = new javax.swing.JToggleButton();
        magnifierToggleButton = new javax.swing.JToggleButton();
        horizontalMirrorToggleButton = new javax.swing.JToggleButton();
        verticalMirrorToggleButton = new javax.swing.JToggleButton();
        copyToggleButton = new javax.swing.JToggleButton();
        pasteToggleButton = new javax.swing.JToggleButton();
        undoToggleButton = new javax.swing.JToggleButton();
        redoToggleButton = new javax.swing.JToggleButton();
        saveToggleButton = new javax.swing.JToggleButton();
        clearToggleButton = new javax.swing.JToggleButton();

        centerPanel.setBackground(new java.awt.Color(128, 128, 128));
        centerPanel.setLayout(new java.awt.GridBagLayout());

        grid.setBackground(new java.awt.Color(0, 153, 153));
        grid.setTileMap(drawMap);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        centerPanel.add(grid, gridBagConstraints);

        gridScrollPane.setViewportView(centerPanel);

        paletteGrid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paletteGrid.setCustomTileSize(new java.lang.Integer(8));
        paletteGrid.setTileMap(new PaletteMap(colorPalette, PALETTE_WIDTH));

        toolButtonGroup.add(selectionToggleButton);
        selectionToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tool_selection.png"))); // NOI18N

        toolButtonGroup.add(magicWandToggleButton);
        magicWandToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tool_magic_wand.png"))); // NOI18N

        toolButtonGroup.add(penToggleButton);
        penToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tool_pen.png"))); // NOI18N

        toolButtonGroup.add(bucketFillToggleButton);
        bucketFillToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tool_bucket_fill.png"))); // NOI18N

        toolButtonGroup.add(lineToggleButton);
        lineToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tool_line.png"))); // NOI18N

        toolButtonGroup.add(circleToggleButton);
        circleToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tool_circle.png"))); // NOI18N

        toolButtonGroup.add(rectangleToggleButton);
        rectangleToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tool_rectangle.png"))); // NOI18N

        toolButtonGroup.add(rectangleFillToggleButton);
        rectangleFillToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tool_rectangle_fill.png"))); // NOI18N

        toolButtonGroup.add(ellipseToggleButton);
        ellipseToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tool_ellipse.png"))); // NOI18N

        toolButtonGroup.add(ellipseFillToggleButton);
        ellipseFillToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tool_ellipse_fill.png"))); // NOI18N

        toolButtonGroup.add(colorPickerToggleButton);
        colorPickerToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tool_color_picker.png"))); // NOI18N

        toolButtonGroup.add(magnifierToggleButton);
        magnifierToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tool_magnifier.png"))); // NOI18N

        toolButtonGroup.add(horizontalMirrorToggleButton);
        horizontalMirrorToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tool_horizontal_mirror.png"))); // NOI18N

        toolButtonGroup.add(verticalMirrorToggleButton);
        verticalMirrorToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tool_vertical_mirror.png"))); // NOI18N

        toolButtonGroup.add(copyToggleButton);
        copyToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/copy.png"))); // NOI18N

        toolButtonGroup.add(pasteToggleButton);
        pasteToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/paste.png"))); // NOI18N

        toolButtonGroup.add(undoToggleButton);
        undoToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tool_undo.png"))); // NOI18N

        toolButtonGroup.add(redoToggleButton);
        redoToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tool_redo.png"))); // NOI18N

        toolButtonGroup.add(saveToggleButton);
        saveToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tool_rectangle.png"))); // NOI18N

        toolButtonGroup.add(clearToggleButton);
        clearToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tool_rectangle.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectionToggleButton)
                            .addComponent(penToggleButton)
                            .addComponent(lineToggleButton))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(circleToggleButton)
                            .addComponent(bucketFillToggleButton)
                            .addComponent(magicWandToggleButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rectangleToggleButton)
                        .addGap(0, 0, 0)
                        .addComponent(rectangleFillToggleButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ellipseToggleButton)
                        .addGap(0, 0, 0)
                        .addComponent(ellipseFillToggleButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(colorPickerToggleButton)
                            .addComponent(horizontalMirrorToggleButton))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(magnifierToggleButton)
                            .addComponent(verticalMirrorToggleButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(copyToggleButton)
                            .addComponent(undoToggleButton))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(redoToggleButton)
                            .addComponent(pasteToggleButton)
                            .addComponent(clearToggleButton)))
                    .addComponent(saveToggleButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gridScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paletteGrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gridScrollPane)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(magicWandToggleButton)
                            .addComponent(selectionToggleButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(penToggleButton)
                            .addComponent(bucketFillToggleButton))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lineToggleButton)
                            .addComponent(circleToggleButton))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rectangleToggleButton)
                            .addComponent(rectangleFillToggleButton))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ellipseToggleButton)
                            .addComponent(ellipseFillToggleButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(magnifierToggleButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(verticalMirrorToggleButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(colorPickerToggleButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(horizontalMirrorToggleButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(copyToggleButton)
                            .addComponent(pasteToggleButton))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(undoToggleButton)
                            .addComponent(redoToggleButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveToggleButton)
                            .addComponent(clearToggleButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paletteGrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				TileMapEditor dialog = new TileMapEditor(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.pack();
				dialog.setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bucketFillToggleButton;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JToggleButton circleToggleButton;
    private javax.swing.JToggleButton clearToggleButton;
    private fr.rca.mapmaker.model.palette.ColorPalette colorPalette;
    private javax.swing.JToggleButton colorPickerToggleButton;
    private javax.swing.JToggleButton copyToggleButton;
    private fr.rca.mapmaker.model.map.TileMap drawMap;
    private javax.swing.JToggleButton ellipseFillToggleButton;
    private javax.swing.JToggleButton ellipseToggleButton;
    private fr.rca.mapmaker.ui.Grid grid;
    private javax.swing.JScrollPane gridScrollPane;
    private javax.swing.JToggleButton horizontalMirrorToggleButton;
    private javax.swing.JToggleButton lineToggleButton;
    private javax.swing.JToggleButton magicWandToggleButton;
    private javax.swing.JToggleButton magnifierToggleButton;
    private fr.rca.mapmaker.ui.Grid paletteGrid;
    private javax.swing.JToggleButton pasteToggleButton;
    private javax.swing.JToggleButton penToggleButton;
    private javax.swing.JToggleButton rectangleFillToggleButton;
    private javax.swing.JToggleButton rectangleToggleButton;
    private javax.swing.JToggleButton redoToggleButton;
    private javax.swing.JToggleButton saveToggleButton;
    private javax.swing.JToggleButton selectionToggleButton;
    private javax.swing.ButtonGroup toolButtonGroup;
    private javax.swing.JToggleButton undoToggleButton;
    private javax.swing.JToggleButton verticalMirrorToggleButton;
    // End of variables declaration//GEN-END:variables
}
